
import java.awt.Component;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;

/**
 * @author larbi
 */
public class Field extends javax.swing.JFrame {
    
    private Matrice MatriceInstance = new Matrice();
    private int OpenN = 0, CountClique = 0;
    private int ImageOpenOneXY[];
    private JToggleButton tbImg1, tbImg2 = null;
    private int ImageOpenTowXY[];
    
    public Field() {
        String NomC = JOptionPane.showInputDialog(this, "Donnez SVP votre Nom", "Votre Nom:", JOptionPane.INFORMATION_MESSAGE);
        initComponents();
        tnom.setText(NomC);
        tclik.setText("0");
        ImageOpenOneXY = new int[2];
        ImageOpenTowXY = new int[2];
        MatriceInstance.GenerateMatriceContenent();

        //Affichage des celleules
//        for (int i = 0; i < MatriceInstance.getMatrixe().length; i++) {
//            for (int j = 0; j < MatriceInstance.getMatrixe().length; j++) {
//                System.out.println(i + " : " + j + " >>> " + ((MonImage) MatriceInstance.getMatrixe()[i][j]).getUrl());
//            }
//        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tb3 = new javax.swing.JToggleButton();
        tb2 = new javax.swing.JToggleButton();
        tb6 = new javax.swing.JToggleButton();
        tb7 = new javax.swing.JToggleButton();
        tb1 = new javax.swing.JToggleButton();
        tb5 = new javax.swing.JToggleButton();
        tb4 = new javax.swing.JToggleButton();
        tb8 = new javax.swing.JToggleButton();
        tb11 = new javax.swing.JToggleButton();
        tb10 = new javax.swing.JToggleButton();
        tb12 = new javax.swing.JToggleButton();
        tb9 = new javax.swing.JToggleButton();
        tb15 = new javax.swing.JToggleButton();
        tb14 = new javax.swing.JToggleButton();
        tb16 = new javax.swing.JToggleButton();
        tb13 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tclik = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Field"));

        tb3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb3ActionPerformed(evt);
            }
        });

        tb2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb2ActionPerformed(evt);
            }
        });

        tb6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb6ActionPerformed(evt);
            }
        });

        tb7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb7ActionPerformed(evt);
            }
        });

        tb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb1ActionPerformed(evt);
            }
        });

        tb5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb5ActionPerformed(evt);
            }
        });

        tb4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb4ActionPerformed(evt);
            }
        });

        tb8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb8ActionPerformed(evt);
            }
        });

        tb11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb11ActionPerformed(evt);
            }
        });

        tb10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb10ActionPerformed(evt);
            }
        });

        tb12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb12ActionPerformed(evt);
            }
        });

        tb9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb9ActionPerformed(evt);
            }
        });

        tb15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb15ActionPerformed(evt);
            }
        });

        tb14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb14ActionPerformed(evt);
            }
        });

        tb16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb16ActionPerformed(evt);
            }
        });

        tb13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
        tb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tb5, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addComponent(tb1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tb6, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb7, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb8, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tb2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb3, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb4, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tb9, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb10, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb11, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb12, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tb13, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb14, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb15, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tb16, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tb1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tb5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tb4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tb8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tb6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tb7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tb13, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tb16, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tb14, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tb15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informations"));

        jLabel1.setText("Nom");

        tnom.setEditable(false);

        jLabel2.setText("Cliques");

        tclik.setEditable(false);

        jLabel4.setText("Best Players");

        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tclik, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tnom, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tclik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Fichier");

        jMenuItem1.setText("Rejouer");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Effacer Tous");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Quitter");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("?");

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void ToggleButtonAction(JToggleButton tb, int PosX, int PosY) {
       
            CountClique++;
            tclik.setText(CountClique + "");
            MonImage img = MatriceInstance.getMatrixe()[PosX][PosY];
            if (OpenN == 0 || OpenN == 1) {
                if (OpenN == 0) {
                    ImageOpenOneXY[0] = PosX;
                    ImageOpenOneXY[1] = PosY;
                    tbImg1 = tb;
                    System.out.println("Open Value : " + OpenN);
                    tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
                } else {
                    ImageOpenTowXY[0] = PosX;
                    ImageOpenTowXY[1] = PosY;
                    tbImg2 = tb;
                    if (CompareOpenImage()) {
                        DisableButtons();
                        OpenN = 0;
                    }
                    System.out.println("Open Value : " + OpenN);
                    tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
                    OpenN++;
                }
                OpenN++;
            } else {
                OpenN = 0;
                System.out.println("Open Value : " + OpenN);
                tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
                ResetAll();
                //tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png"))); // NOI18N
            }
//        MonImage img = MatriceInstance.getMatrixe()[PosX][PosY];
//        if (OpenN == 0) {
//            ImageOpenOneXY[0] = PosX;
//            ImageOpenOneXY[1] = PosY;
//            tbImg1 = tb;
//            System.out.println("Open Value : " + OpenN);
//            tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
//            OpenN++;
//        } else if (OpenN == 1) {
//            ImageOpenTowXY[0] = PosX;
//            ImageOpenTowXY[1] = PosY;
//            tbImg2 = tb;
//            if (CompareOpenImage()) {
//                DisableButtons();
//                OpenN = 0;
//            }else{
//            System.out.println("Open Value : " + OpenN);
//            tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
//            }
//            
//           OpenN++;
//        } else {
//            OpenN = 0;
//            System.out.println("Open Value : " + OpenN);
//            tb.setIcon(new javax.swing.ImageIcon(getClass().getResource(img.getUrl()))); // NOI18N
//            ResetAll();
//        }
       
    }
    private void tb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb2ActionPerformed
        ToggleButtonAction(tb2, 0, 1);
    }//GEN-LAST:event_tb2ActionPerformed
    
    private void tb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb1ActionPerformed
        ToggleButtonAction(tb1, 0, 0);
        
    }//GEN-LAST:event_tb1ActionPerformed
    
    private void tb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb3ActionPerformed
        ToggleButtonAction(tb3, 0, 2);
    }//GEN-LAST:event_tb3ActionPerformed
    
    void ResetAll() {
        JToggleButton Tab[] = {tb1, tb2, tb3, tb4, tb5, tb6, tb7, tb8, tb9, tb10, tb11, tb12, tb13, tb14, tb15, tb16};
        for (JToggleButton tb : Tab) {
            if (tb.isEnabled()) {
                tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png")));
                tb.setSelected(false);
            }
        }
    }
    
    void DisableButtons() {
        tbImg1.setEnabled(false);
        tbImg2.setEnabled(false);
    }
    
    boolean CompareOpenImage() {
        //Tableau des images
        MonImage Tab[][] = MatriceInstance.getMatrixe();
        MonImage Img1 = Tab[ImageOpenOneXY[0]][ImageOpenOneXY[1]];
        MonImage Img2 = Tab[ImageOpenTowXY[0]][ImageOpenTowXY[1]];
        if (Img1.getId() == Img2.getId()) {
            return true;
        } else {
            return false;
        }
    }
    private void tb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb4ActionPerformed
        ToggleButtonAction(tb4, 0, 3);
    }//GEN-LAST:event_tb4ActionPerformed
    
    private void tb8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb8ActionPerformed
        ToggleButtonAction(tb8, 1, 3);
    }//GEN-LAST:event_tb8ActionPerformed
    
    private void tb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb12ActionPerformed
        ToggleButtonAction(tb12, 2, 3);
    }//GEN-LAST:event_tb12ActionPerformed
    
    private void tb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb16ActionPerformed
        ToggleButtonAction(tb16, 3, 3);
    }//GEN-LAST:event_tb16ActionPerformed
    
    private void tb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb5ActionPerformed
        ToggleButtonAction(tb5, 1, 0);
    }//GEN-LAST:event_tb5ActionPerformed
    
    private void tb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb6ActionPerformed
        ToggleButtonAction(tb6, 1, 1);
    }//GEN-LAST:event_tb6ActionPerformed
    
    private void tb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb7ActionPerformed
        ToggleButtonAction(tb7, 1, 2);
    }//GEN-LAST:event_tb7ActionPerformed
    
    private void tb9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb9ActionPerformed
        ToggleButtonAction(tb9, 2, 0);
    }//GEN-LAST:event_tb9ActionPerformed
    
    private void tb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb10ActionPerformed
        ToggleButtonAction(tb10, 2, 1);
    }//GEN-LAST:event_tb10ActionPerformed
    
    private void tb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb11ActionPerformed
        ToggleButtonAction(tb11, 2, 2);
    }//GEN-LAST:event_tb11ActionPerformed
    
    private void tb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb13ActionPerformed
        ToggleButtonAction(tb13, 3, 0);
    }//GEN-LAST:event_tb13ActionPerformed
    
    private void tb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb14ActionPerformed
        ToggleButtonAction(tb14, 3, 1);
    }//GEN-LAST:event_tb14ActionPerformed
    
    private void tb15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb15ActionPerformed
        ToggleButtonAction(tb15, 3, 2);
    }//GEN-LAST:event_tb15ActionPerformed
    boolean isAllToggleButtonAreDisabled() {
        JToggleButton Tab[] = {tb1, tb2, tb3, tb4, tb5, tb6, tb7, tb8, tb9, tb10, tb11, tb12, tb13, tb14, tb15, tb16};
        for (JToggleButton tb : Tab) {
            if (tb.isEnabled()) {
                return false;
            }
        }
        return true;
    }
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//String NomC = JOptionPane.showInputDialog(this, "Donnez SVP votre Nom", "Votre Nom:", JOptionPane.INFORMATION_MESSAGE);
        MatriceInstance = new Matrice();
        MatriceInstance.GenerateMatriceContenent();
        JToggleButton Tab[] = {tb1, tb2, tb3, tb4, tb5, tb6, tb7, tb8, tb9, tb10, tb11, tb12, tb13, tb14, tb15, tb16};
        for (JToggleButton tb : Tab) {
            tb.setEnabled(true);
            tb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/def.png")));
            tb.setSelected(false);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Field.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new Field().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToggleButton tb1;
    private javax.swing.JToggleButton tb10;
    private javax.swing.JToggleButton tb11;
    private javax.swing.JToggleButton tb12;
    private javax.swing.JToggleButton tb13;
    private javax.swing.JToggleButton tb14;
    private javax.swing.JToggleButton tb15;
    private javax.swing.JToggleButton tb16;
    private javax.swing.JToggleButton tb2;
    private javax.swing.JToggleButton tb3;
    private javax.swing.JToggleButton tb4;
    private javax.swing.JToggleButton tb5;
    private javax.swing.JToggleButton tb6;
    private javax.swing.JToggleButton tb7;
    private javax.swing.JToggleButton tb8;
    private javax.swing.JToggleButton tb9;
    private javax.swing.JTextField tclik;
    private javax.swing.JTextField tnom;
    // End of variables declaration//GEN-END:variables
}
